### ISSUE TITLE
Pagination seems broken in the features table

### ISSUE THREAD

**Issue by alexbarrera** [ReddyLab/cegs-portal#13]
Genomic range searches seem to be working fine but the table showing the results does not load new elements when clicking either *next* or *last >>* buttons.

**Comment by tncowart** [comment]
https://test-cegsptl.dkstest.dhe.duke.edu/search/results/?query=chr11:33807991-33920400 for instance -- a region with no reference genome

**Comment by alexbarrera** [comment]
There should be a gene there both in [hg19](http://genome.ucsc.edu/cgi-bin/hgTracks?db=hg19&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr11%3A33807991%2D33920400&hgsid=1467132785_DYLhp6qK2u7qntokz3LGnqmWx4mY) and [hg38](http://genome.ucsc.edu/cgi-bin/hgTracks?db=hg38&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr11%3A33807991%2D33920400&hgsid=1467132785_DYLhp6qK2u7qntokz3LGnqmWx4mY)

**Comment by tncowart** [comment]
I think that might be a different issue: https://github.com/ReddyLab/cegs-portal/issues/16
